### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by TomaszPekalski** [simPod/PhpKafkaBundle#25]
Hi Could You create some simple examples in readme how we can use methods from class KafkaConsumer?

**Comment by simPod** [comment]
I'll be migrating this to PHP 8 and do some maintenance. Will look into it while in process.

**Comment by TomaszPekalski** [comment]
Thank You for reply, but do You have some blog or github project with some
examples with current application version :)?

pt., 22 sty 2021, 23:22 użytkownik Simon Podlipsky <notifications@github.com>
napisał:

**Comment by simPod** [comment]
Now I'm trying to understand what you're asking. What is missing in readme? There's named consumer example.

**Comment by TomaszPekalski** [comment]
Hi Simon,

In readme You used KafkaBatchConsumer, which not exists in your code ;)

And I want to ask, do You have some examples how to use KafkaConsumer.php,
but when I wrote it i found this in https://github.com/simPod/PhpKafka, so
maybe in readme would be nice put some link to it ?

[image: BA8355CA-7D01-4F4C-AF23-7B6B2ACC6AE0.png]


Z pozdrowieniami / Kind regards

*Tomasz Pękalski*



sob., 23 sty 2021 o 13:08 Simon Podlipsky <notifications@github.com>
napisał(a):

**Comment by simPod** [comment]
There was some attempt to do batching a while ago. Currently there's no batch consuming support in rdkafka. But see this

https://github.com/simPod/PhpKafka#batching-consumer

I'll have to update readme here

**Comment by simPod** [comment]
I did some updates, does it work 4 u?

**Comment by TomaszPekalski** [comment]
thank You, we will check all - next week


czw., 18 mar 2021 o 20:45 Simon Podlipsky ***@***.***>
napisał(a):
