### ISSUE TITLE
Restarting consumer to minimize memory leaks

### ISSUE THREAD

**Issue by raph007** [simPod/PhpKafkaBundle#37]
Hello,

As Kafka consumer is long running PHP process I was wondering about restarting it from time to time... I very often see parameters such as "max-time" for bundles related to RabbitMQ. 
Is there a reason there's no such parameter in this bundle or maybe it's not needed?

I'm new to Kafka and any thoughts in this matter would be very useful for me. :)

**Comment by simPod** [comment]
Hi, IIRC I could run RabbitMQ without that max-time as well. Though such parameter should not be needed here.

**Comment by raph007** [comment]
So just solution such as Supreviord in case consumer went down will do the job?

**Comment by simPod** [comment]
Yes. Also it's good to let it sleep for a second so it does not restart instantly in case of some bug. When it exits too fast, supervisor won't restart it (!FATAL Exited too quickly (process log may have details)`).
